language: rust

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.9
    packages:
      # for building MPI libraries
      - build-essential
      - gfortran
      # bindgen dependency
      - libclang-3.9-dev
      # libffi dependency
      - texinfo

env:
  global:
    # GH_TOKEN=...
    - secure: "b/XSfdfqZZCP+hG65bqi+wPPh0z5lMRCL7X4Y0vNPt01WGqu851RHF6XGvkBa8MQWWYylDAAZTFWHDHG0uAb94Dpvo2+XpU4PtRrTUd52lN3U66bRyR1H5wRlhCBYpqnke7S3zP2XKvHfTUFNPyF6NliCVKPsntTPsb7szYevZzYzIBIjsPq5IbUqezsV6aVvjJ6wcIjMdzhsDafefNGxEkSis6XhSPXif02enyglKCN6qhPcd+RdaCP4NyUhxxyNO7w6tGooCo1V534/EPH08u0tU78htV/TNzlvobjAvxrC4lnCY7MJW1lFkJL9tzTo1LC2xaFMzLwzsYr3b+PCBg94Iz4OcA7le630SiZC0iI2lLL7xsaSp+qSFK1YTp0nPH0LXE67XesAjFHnRh/EroJK9UK58L+enBWUzsm6Q4ey2k+AaOw9IkHvDXtgjAJknmG+na3dRVbmEetxVkxm9yucAzUxw12h4ZHwYv2LPWDtu+CL7TbUItqgHIkw0AGGX5eII3uThOib+aKuG8g86G16XHQ2aXEZmkA9BdXqlLG4P5qSDN1SiO+s8W6Q2WVgVHlk4tlpSEOXXx0AbeBndQzRAFHKEyBeVq3NKYLncikHjndR1/jvzTMSVIli2ptbUJbXTZMTT5B05QWIR9Xh95gxKunc1kfNJ6YSEhVDf0="
    # CRATES_IO_TOKEN=...
    - secure: "FYoav+St+90i6AQzyMw+NJdtktG2UMK7szt7ar88ww7bkkCd9I9qgtqqW6mopzpnguRhBusxoCsmiroFbXVO1R3vSP1ugECUTDCK7x/Tqkc/wa0MOqlmBneG+bZOF3YjiDTfaAIUI8r10RstfRhRwIKgZI3vE/8TEgTGlWW+cZuHaz7U4wesHUY+euuSoLuD7XrlI1N9EBAbHwTtLpfHoONSw8fxVQc0nQ7vTBrC+UQiRZA8oFP7qpJ/9xfsCMWSyVihuSzdHoCRIxCs+rWROBpULAqvPa0vYdxE7oQHPwbaQ8bsv088Mowjaq5Dp8NimodimQsx7D58g/e+INEk9q3dwj/RN0iMgNYqhYv9Wu+vMWNMbvReSHlJtIYWtl2varXQI2hOPC/+6OhfzlAT1hBsrkJjZ6bQ9Yv9NUGNQHNrFvdCKOEvSG3wHNB10mfBB/KSVzB/ya8suEBR07CjzbrzTlH2SUYfSHS5iNbP791kAYp2MyMn69ZajeEZ3iYwwG2lHH2CONB/QiAX6ZDc5J3jM8gmxu2S5QkZkZieBnDZG/OsYjOw7Zka3ktlGW+Khn3RRRsDYMrpAN5qmiEO6vdDP/XcRZw4ERfHQd8A9kEhnhJGOlg6KGyNM0pi7s4IX8VWkbxAmY53HqsyK1eagIVLsxkzCn3GKfVQuufHBBc="

jobs:
  include:
    # Special format job
    - name: "cargo fmt"
      install:
      - rustup component add rustfmt
      script:
      - cargo fmt --all
      - git diff --exit-code
      cache:
    # Build matrix of MPI builds
    # We put the latest versions of MPICH, OpenMPI, and MS-MPI first. Everything
    # else comes later.
    - name: "MPICH 3.3"
      env: LIBCLANG_PATH=/usr/lib/llvm-3.9/lib MPI_LIBRARY=mpich MPI_LIBRARY_VERSION=3.3 RELEASE_CONFIG=true
      rust: stable
      os: linux
    - name: "OpenMPI 4.0.1"
      env: LIBCLANG_PATH=/usr/lib/llvm-3.9/lib MPI_LIBRARY=openmpi MPI_LIBRARY_VERSION=4.0.1 RELEASE_CONFIG=false
      rust: stable
      os: linux
    - name: "MS-MPI 10.0.0"
      env: MPI_LIBRARY=msmpi MPI_LIBRARY_VERSION=10.0.0 RELEASE_CONFIG=false
      rust: stable
      os: windows
    - name: "MPICH 3.2.1"
      env: LIBCLANG_PATH=/usr/lib/llvm-3.9/lib MPI_LIBRARY=mpich MPI_LIBRARY_VERSION=3.2.1 RELEASE_CONFIG=false
      rust: stable
      os: linux
    - name: "MPICH 3.1.4"
      env: LIBCLANG_PATH=/usr/lib/llvm-3.9/lib MPI_LIBRARY=openmpi MPI_LIBRARY_VERSION=3.1.4 RELEASE_CONFIG=false
      rust: stable
      os: linux
    - name: "OpenMPI 3.0.4"
      env: LIBCLANG_PATH=/usr/lib/llvm-3.9/lib MPI_LIBRARY=openmpi MPI_LIBRARY_VERSION=3.0.4 RELEASE_CONFIG=false
      rust: stable
      os: linux
    - name: "MPICH 3.3 [Rust beta]"
      env: LIBCLANG_PATH=/usr/lib/llvm-3.9/lib MPI_LIBRARY=mpich MPI_LIBRARY_VERSION=3.3 RELEASE_CONFIG=false
      rust: beta
      os: linux
    - name: "MPICH 3.3 [Rust nightly]"
      env: LIBCLANG_PATH=/usr/lib/llvm-3.9/lib MPI_LIBRARY=mpich MPI_LIBRARY_VERSION=3.3 RELEASE_CONFIG=false
      rust: nightly
      os: linux
    - name: "MS-MPI 10.0.0 [Rust nightly]"
      env: MPI_LIBRARY=msmpi MPI_LIBRARY_VERSION=10.0.0 RELEASE_CONFIG=false
      rust: nightly
      os: windows
  allow_failures:
    - rust: nightly

install:
  # Linux set-up
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sh ci/install-mpi.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export MPI_PREFIX="${HOME}/opt/${MPI_LIBRARY}-${MPI_LIBRARY_VERSION}"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export PATH="${HOME}/.local/bin:${MPI_PREFIX}/bin${PATH:+":${PATH}"}"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export LD_LIBRARY_PATH="${MPI_PREFIX}/lib${LD_LIBRARY_PATH:+":${LD_LIBRARY_PATH}"}"; fi
  # Windows set-up
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then rustup default $TRAVIS_RUST_VERSION-x86_64-pc-windows-msvc; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then sh ci/install-mpi-windows.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then export MSMPI_BIN="C:\\Program Files\\Microsoft MPI\\Bin\\"; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then export MSMPI_INC="C:\\Program Files (x86)\\Microsoft SDKs\\MPI\\Include\\"; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then export MSMPI_LIB32="C:\\Program Files (x86)\\Microsoft SDKs\\MPI\\Lib\\x86\\"; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then export MSMPI_LIB64="C:\\Program Files (x86)\\Microsoft SDKs\\MPI\\Lib\\x64\\"; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then export PATH="${HOME}/.cargo/bin:${MSMPI_BIN}${PATH:+":${PATH}"}"; fi
  # Global set-up
  - cargo install --force cargo-mpirun
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
      rustup component add clippy;
    fi

script:
  - env RUSTFLAGS="--deny warnings" cargo build --no-default-features -v
  - env RUSTFLAGS="--deny warnings" cargo build --all-features -v
  - env RUSTFLAGS="--deny warnings" cargo test --all --all-features -v
  - env RUSTFLAGS="--deny warnings" sh ci/run-examples.sh
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
      env RUSTFLAGS="--deny warnings" cargo clippy -v --all --examples --tests;
    fi

before_deploy:
  # Login to cates.io
  - cargo login "${CRATES_IO_TOKEN}"
  # Package crates
  - cargo package -v --no-verify
  - cargo package -v --no-verify --manifest-path build-probe-mpi/Cargo.toml
  - cargo package -v --no-verify --manifest-path mpi-sys/Cargo.toml
  # Build docs
  - cargo doc -v
  - echo "<meta http-equiv=refresh content=0;url=mpi/index.html>" >> target/doc/index.html

deploy:
  # Build and upload documentation to GitHub pages
  - provider: pages
    github_token: $GH_TOKEN
    local_dir: target/doc
    skip_cleanup: true
    on:
      tags: true
      condition: "${RELEASE_CONFIG} = true && ${TRAVIS_TAG} = mpi-?.?.?"
  # Deploy the mpi crate to GitHub releases
  - provider: releases
    api_key: $GH_TOKEN
    file: "target/package/${TRAVIS_TAG}.crate"
    skip_cleanup: true
    on:
      tags: true
      condition: "${RELEASE_CONFIG} = true && ${TRAVIS_TAG} = mpi-?.?.?"
  # Deploy the build-probe-mpi crate to GitHub releases
  - provider: releases
    api_key: $GH_TOKEN
    file: "target/package/${TRAVIS_TAG}.crate"
    skip_cleanup: true
    on:
      tags: true
      condition: "${RELEASE_CONFIG} = true && ${TRAVIS_TAG} = build-probe-mpi-?.?.?"
  # Deploy the mpi-sys crate to GitHub releases
  - provider: releases
    api_key: $GH_TOKEN
    file: "target/package/${TRAVIS_TAG}.crate"
    skip_cleanup: true
    on:
      tags: true
      condition: "${RELEASE_CONFIG} = true && ${TRAVIS_TAG} = mpi-sys-?.?.?"
  # Deploy the mpi crate to crates.io
  - provider: script
    script: "ci/deploy-crate.sh mpi"
    skip_cleanup: true
    on:
      tags: true
      condition: "${RELEASE_CONFIG} = true && ${TRAVIS_TAG} = mpi-?.?.?"
  # Deploy the build-probe-mpi crate to crates.io
  - provider: script
    script: "ci/deploy-crate.sh build-probe-mpi"
    skip_cleanup: true
    on:
      tags: true
      condition: "${RELEASE_CONFIG} = true && ${TRAVIS_TAG} = build-probe-mpi-?.?.?"
  # Deploy the mpi-sys crate to crates.io
  - provider: script
    script: "ci/deploy-crate.sh mpi-sys"
    skip_cleanup: true
    on:
      tags: true
      condition: "${RELEASE_CONFIG} = true && ${TRAVIS_TAG} = mpi-sys-?.?.?"

cache:
  cargo: true
  directories:
    - $HOME/opt
