[package]
name = "mpi"
version = "0.4.0"
authors = ["Benedikt Steinbusch <ben@rockshrub.de>"]
description = "Message Passing Interface bindings for Rust"
homepage = "https://github.com/bsteinb/rsmpi"
repository = "https://github.com/bsteinb/rsmpi"
documentation = "http://bsteinb.github.io/rsmpi/"
readme = "README.md"
keywords = [ "message-passing", "parallel" ]
license = "MIT OR Apache-2.0"
build = "build.rs"

[dependencies]
conv = "0.3"

[build-dependencies]
gcc = "0.3"
bindgen = { git = "https://github.com/crabtw/rust-bindgen.git", rev = "0433980286a5264e3d69214aa42e314c37238cf6" }
build-probe-mpi = { path = "./build-probe-mpi" }

#[dependencies.c_import]
#git = "https://github.com/vojtechkral/rust-c-import.git"

[features]
default=[]
lint = [ "clippy" ]
clippy = []
